name       : jemalloc
version    : 4.0.4
release    : 4
source     :
    - https://github.com/jemalloc/jemalloc/releases/download/4.0.4/jemalloc-4.0.4.tar.bz2 : 3fda8d8d7fcd041aa0bebbecd45c46b28873cf37bd36c56bf44961b36d0f42d0
license    : BSD
summary    : jemalloc is a general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
description: |
    jemalloc is a general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
patterns: 
    -  [/usr/bin, /usr/lib64/*.so*,/usr/share/doc/]
builddeps  : perl
setup      : |
    %configure --prefix=/usr --disable-static --disable-fill
build      : |
    %make
install    : |
    %make_install
