name       : jemalloc
version    : 4.0.3
release    : 3
source     :
    - https://github.com/jemalloc/jemalloc/releases/download/4.0.3/jemalloc-4.0.3.tar.bz2 : f1f7686c30eebf58261ae235752a0251d092ca13184b7fe0447b7915ad72f6d6
license    : BSD
summary    : jemalloc is a general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
description: |
    jemalloc is a general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
patterns: 
    -  [/usr/bin, /usr/lib64/*.so*,/usr/share/doc/]
builddeps  : perl
setup      : |
    %configure --prefix=/usr --disable-static --disable-fill
build      : |
    %make
install    : |
    %make_install
