name       : jemalloc
version    : 4.5.0
release    : 7
source     :
    - https://github.com/jemalloc/jemalloc/releases/download/4.5.0/jemalloc-4.5.0.tar.bz2 : 9409d85664b4f135b77518b0b118c549009dc10f6cba14557d170476611f6780
license    : BSD-2-Clause
component  : programming
summary    : jemalloc is a general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
description: |
    jemalloc is a general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
builddeps  :
    - perl
setup      : |
    %configure --prefix=/usr --disable-static --disable-fill
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
