name       : jemalloc
version    : 4.4.0
release    : 6
source     :
    - https://github.com/jemalloc/jemalloc/releases/download/4.4.0/jemalloc-4.4.0.tar.bz2 : a7aea63e9718d2f1adf81d87e3df3cb1b58deb86fc77bad5d702c4c59687b033
license    : BSD-2-Clause
component  : programming
summary    : jemalloc is a general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
description: |
    jemalloc is a general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
builddeps  :
    - perl
setup      : |
    %configure --prefix=/usr --disable-static --disable-fill
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
