name       : jemalloc
version    : 5.1.0
release    : 10
source     :
    - https://github.com/jemalloc/jemalloc/releases/download/5.1.0/jemalloc-5.1.0.tar.bz2 : 5396e61cc6103ac393136c309fae09e44d74743c86f90e266948c50f3dbb7268
license    : BSD-2-Clause
component  : programming
summary    : jemalloc is a general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
description: |
    jemalloc is a general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
builddeps  :
    - perl
setup      : |
    %configure --prefix=/usr --disable-static --disable-fill
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
