name       : jemalloc
version    : 4.1.0
release    : 5
source     :
    - https://github.com/jemalloc/jemalloc/releases/download/4.1.0/jemalloc-4.1.0.tar.bz2 : fad06d714f72adb4265783bc169c6d98eeb032d57ba02d87d1dcb4a2d933ec8e
license    : BSD
summary    : jemalloc is a general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
description: |
    jemalloc is a general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
patterns: 
    -  [/usr/bin, /usr/lib64/*.so*,/usr/share/doc/]
builddeps  : perl
setup      : |
    %configure --prefix=/usr --disable-static --disable-fill
build      : |
    %make
install    : |
    %make_install
